openapi: 3.0.3
info:
  title: User API
  version: 1.0.0

paths:
  /users/{id}:
    get:
      tags:
        - Users
      operationId: getUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDto"

  /trainings/insights/:
    get:
      tags:
        - Insights
      operationId: getInsight
      parameters:
        - name: id
          in: query
          required: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InsightDto"


components:
  schemas:
    UserDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
    InsightDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        insight:
          type: string
        updated_at:
          type: string
          format: date-time
