openapi: 3.0.3
info:
  title: User API
  version: 1.0.0

paths:
  /trainings/insights:
    get:
      tags:
        - Insights
      operationId: getInsights
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TrainingAnalysisDto"

components:
  schemas:
    TrainingAnalysisDto:
      type: object
      properties:
        loadLevel:
          type: string
        nextWeekRecommendation:
          type: string
        watchOut:
          type: string
        observations:
          type: array
          items:
            type: string
